# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	T_n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	P_n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	H_n=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T_285 = P_165 = H_143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

def triangle_number(n)
  n * (n + 1) / 2
end

def pentagonal_number(n)
  n * (3 * n - 1) / 2
end

def hexagonal_number(n)
  n * (2 * n - 1)
end

tri_idx = 280
pent_idx = 160
hex_idx = 144

tri_num = triangle_number(tri_idx)
pent_num = pentagonal_number(pent_idx)
hex_num = hexagonal_number(hex_idx)


while hex_num != pent_num || hex_num != tri_num do
  if pent_num < hex_num
    pent_idx += 1
    pent_num = pentagonal_number(pent_idx)
  elsif pent_num == hex_num
    if tri_num < hex_num
      tri_idx += 1
      tri_num = triangle_number(tri_idx)
    else
      hex_idx += 1
      hex_num = hexagonal_number(hex_idx)
    end
  else
    hex_idx += 1
    hex_num = hexagonal_number(hex_idx)
  end
end

puts '=================='
puts "T_#{tri_idx} = #{tri_num}"
puts "P_#{pent_idx} = #{pent_num}"
puts "H_#{hex_idx} = #{hex_num}"
